# Using Data Mining Techniques into Real Estates Industry

**Authors**:
-  _Madalina-Alina Racovita, 1st year master's student on Computational Optimization at Faculty of Computer Science, UAIC, Iasi, Romania_
-  _Buterchi Andreea, 1st year master's student on Advanced Studies in Computer Science at Faculty of Computer Science, UAIC, Iasi, Romania_

![title](real-estates.jpg)

<h1>Data Mining Laboratory - 1st Task. Exploratory Data Analysis <span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Using-Data-Mining-Techniques-into-Real-Estates-Industry" data-toc-modified-id="Using-Data-Mining-Techniques-into-Real-Estates-Industry-1">Using Data Mining Techniques into Real Estates Industry</a></span><ul class="toc-item"><li><span><a href="#Motivation" data-toc-modified-id="Motivation-1.1">Motivation</a></span></li><li><span><a href="#Introduction" data-toc-modified-id="Introduction-1.2">Introduction</a></span></li><li><span><a href="#Import-dependencies-&amp;-environment-configuration" data-toc-modified-id="Import-dependencies-&amp;-environment-configuration-1.3">Import dependencies &amp; environment configuration</a></span></li><li><span><a href="#Load-dataframes" data-toc-modified-id="Load-dataframes-1.4">Load dataframes</a></span><ul class="toc-item"><li><span><a href="#RCON-dataframes-loading" data-toc-modified-id="RCON-dataframes-loading-1.4.1">RCON dataframes loading</a></span></li><li><span><a href="#RSFR-dataframes-loading" data-toc-modified-id="RSFR-dataframes-loading-1.4.2">RSFR dataframes loading</a></span></li></ul></li><li><span><a href="#Columns-description" data-toc-modified-id="Columns-description-1.5">Columns description</a></span></li><li><span><a href="#Investigation-of-the-RCON-and-RSFR-dataset" data-toc-modified-id="Investigation-of-the-RCON-and-RSFR-dataset-1.6">Investigation of the RCON and RSFR dataset</a></span></li><li><span><a href="#Non-numerical-columns" data-toc-modified-id="Non-numerical-columns-1.7">Non-numerical columns</a></span></li></ul></li></ul></div>

## Motivation

The way in which the value of a house is currently set in the real estate industry is not necessarily statistically robust. There are two states in which a person can be in the real estate market: seller or buyer. Regardless of the hypostase in which a given person is, it is a certain fact she may under evaluate or she may overestimate that property by reasoning subjectively. 

Given the hundreds of property sales that occur in one specific period of time, it is logical to evaluate and analyze the sales from multiple
points of view to establish a more accurate value for a house with a specific characterization. Regression analysis is a statistical approach of modeling the relationship between one or more independent or explanatory variables (characteristics of a house), and a dependent variable (the value or selling price of the house).The already created models have proven that using regression analysis is a viable way to better establish an estimate of the true value of a house.  Classification can also help in making distinctions between different properties. 


## Introduction 

This notebook is attempting to achieve **explanatory data analysis**, **feature selection** and **feature engineering** required for the task of building a regression / classification model that will be able to predict the value of an independent variable (for instance, the sale price of a house in the case of regression or the type of the property in a classification context) as accurately as possible by minimizing a cost error function.
![title](house-banner.png)

## Import dependencies & environment configuration

In [1]:
import pandas as pd
from scipy.stats import skew
import os
pd.set_option('display.max_columns', None)

## Load dataframes

In [2]:
os.listdir('./Data')

['RCON_12011.assessor.tsv',
 'RCON_53033.assessor.tsv',
 'RSFR_12011.assessor.tsv',
 'RSFR_53033.assessor.tsv']

### RCON dataframes loading

In [3]:
import pandas as pd
from scipy.stats import skew

In [4]:
df_rcon1 = pd.read_csv("./Data/RCON_12011.assessor.tsv", sep = "\t")

In [5]:
df_rcon1.shape

(21637, 63)

In [6]:
df_rcon2 = pd.read_csv("./Data/RCON_53033.assessor.tsv", sep = "\t")

In [7]:
df_rcon2.shape

(11265, 63)

We are going to **merge** those two dataframes concerning **RCON real estates** in the purpose of an overview analysis.

In [8]:
df_rcon = pd.concat([df_rcon1, df_rcon2])
df_rcon.shape

(32902, 63)

In [9]:
print("Number of observations in RCON dataset: ", df_rcon.shape[0])
print("Number of predictors in RCON dataset: ", df_rcon.shape[1] - 1)

Number of observations in RCON dataset:  32902
Number of predictors in RCON dataset:  62

### RSFR dataframes loading

In [10]:
df_rsfr1 = pd.read_csv("./Data/RSFR_12011.assessor.tsv", sep = "\t")

In [11]:
df_rsfr1.shape

(32838, 63)

In [12]:
df_rsfr2 = pd.read_csv("./Data/RSFR_53033.assessor.tsv", sep = "\t")

In [13]:
df_rsfr2.shape

(53041, 63)

As did in the case of RCON dataframe, the same step is going to be proceed for the RSFR real estates dataframe: there **are going to be merged the __df_rsfr1__ and __df_rsfr2__ dataframes**.

In [14]:
df_rsfr = pd.concat([df_rsfr1, df_rsfr2])

In [15]:
print("Number of observations in RSFR dataset: ", df_rsfr.shape[0])
print("Number of predictors in RSFR dataset: ", df_rsfr.shape[1] - 1)

Number of observations in RSFR dataset:  85879
Number of predictors in RSFR dataset:  62

## Columns description

-  **CountyFipsCode** = five-digit Federal Information Processing Standards code which uniquely identified counties and county equivalents in the United States
-  **BuildingCode** = 
-  **StructureCode** = 
-  **StructureNbr** = 
-  **LandSqft** = 
-  **LivingSqft** = 
-  **GarageSqft** = 
-  **BasementSqft** = 
-  **BasementFinishedSqft** = 
-  **AtticSqft** = 
-  **Bedrooms** = 
-  **TotalRooms** = 
-  **TotalBaths** = 
-  **FirePlaces** = 
-  **YearBuilt** = 
-  **EffectiveYearBuilt** = 
-  **Condition** = 
-  **ConditionCode** = 
-  **Quality** = 
-  **QualityCode** = 
-  **GarageCarportCode** = 
-  **GarageNoOfCars** = 
-  **HasPatioPorch** = 
-  **PatioPorchCode** = 
-  **HasPool** = 
-  **PoolCode** = 
-  **Zonning** = 
-  **LandValue** = 
-  **ImprovementValue** = 
-  **TotalValue** = 
-  **AssessedYear** = 
-  **PropTaxAmount** = 
-  **City** = the city where the real estate can be found
-  **State** =  the state where the real estate can be found
-  **Zip** = zip code 
-  **Latitude** = latitude coordinate for the house
-  **Longitude** = longitude coordinate for the house
-  **BuildingShapeCode** = 
-  **ConstructionCode** = 
-  **Stories** = 
-  **UnitsInBuilding** = 
-  **FoundationCode** = 
-  **ExteriorCode** = 
-  **RoofCode** = 
-  **CoolingCode** = 
-  **HeatingCode** = 
-  **HeatingSourceCode** = 
-  **IsWaterfront** = 
-  **View** = numerical variable 
-  **ViewScore** = 
-  **LastSaleDate** = 
-  **LastSalePrice** = 
-  **DocType** = 
-  **DeedType** = 
-  **TransType** = 
-  **ArmsLengthFlag** = 
-  **DistressCode** = 
-  **StatusDate** = 
-  **SellDate** = 
-  **SellPrice** = 
-  **OwnerOccupied** = 
-  **DistrsdProp** = 
-  **IsFixer**

## Investigation of the RCON and RSFR dataset

In [16]:
df_rcon.head()

,CountyFipsCode,BuildingCode,StructureCode,StructureNbr,LandSqft,LivingSqft,GarageSqft,BasementSqft,BasementFinishedSqft,AtticSqft,Bedrooms,TotalRooms,TotalBaths,FirePlaces,YearBuilt,EffectiveYearBuilt,Condition,ConditionCode,Quality,QualityCode,GarageCarportCode,GarageNoOfCars,HasPatioPorch,PatioPorchCode,HasPool,PoolCode,Zonning,LandValue,ImprovementValue,TotalValue,AssessedYear,PropTaxAmount,City,State,Zip,Latitude,Longitude,BuildingShapeCode,ConstructionCode,Stories,UnitsInBuilding,FoundationCode,ExteriorCode,RoofCode,CoolingCode,HeatingCode,HeatingSourceCode,IsWaterfront,View,ViewScore,LastSaleDate,LastSalePrice,DocType,DeedType,TransType,ArmsLengthFlag,DistressCode,StatusDate,SellDate,SellPrice,OwnerOccupied,DistrsdProp,IsFixer
0,12011,NaN,NaN,1,3999,1180,0,0,0,0,2,0,2.0,0,1977,0,AVE,2,QAV,6,NaN,0,False,NaN,False,NaN,NaN,6059,54499,60560,2016,1616.0,NaN,FL,33321,26.206,-80.265,NaN,1,0,1,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,0,1998-03-27 00:00:00,40000,NaN,NaN,R,True,NaN,2017-02-10 00:00:00,1998-03-27,40000.0,False,0,0.0
1,12011,NaN,NaN,1,3999,800,0,0,0,0,1,0,1.5,0,1973,0,AVE,2,QAV,6,NaN,0,False,NaN,False,NaN,NaN,5079,45759,50840,2016,1560.0,NaN,FL,33319,26.171,-80.231,NaN,1,0,1,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,0,2006-10-06 00:00:00,100000,W,NaN,R,True,NaN,2017-02-10 00:00:00,2006-10-06,100000.0,False,0,0.0
2,12011,NaN,NaN,1,3999,825,0,0,0,0,2,0,1.0,0,1968,0,AVE,2,QAV,6,NaN,0,False,NaN,False,NaN,RM-18,7439,66979,74420,2016,420.0,NaN,FL,33020,26.018,-80.155,NaN,1,0,1,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,0,2003-12-05 00:00:00,78000,G,NaN,R,True,NaN,2017-02-10 00:00:00,2003-12-05,78000.0,True,0,0.0
3,12011,NaN,NaN,1,3999,750,0,0,0,0,1,0,1.5,0,1989,0,AVE,2,QAV,6,NaN,0,False,NaN,False,NaN,NaN,4929,44329,49260,2016,1300.0,NaN,FL,33063,26.263,-80.232,NaN,1,0,1,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,0,2006-11-28 00:00:00,111500,W,NaN,R,True,NaN,2017-02-10 00:00:00,2006-11-28,111500.0,True,0,0.0
4,12011,NaN,NaN,1,3999,1250,0,0,0,0,2,0,2.0,0,1988,0,AVE,2,QAV,6,NaN,0,False,NaN,False,NaN,R-4C,13959,125669,139630,2016,880.0,NaN,FL,33442,26.297,-80.158,NaN,1,0,1,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,0,2009-03-04 00:00:00,85500,G,NaN,R,True,S,2017-02-10 00:00:00,2009-03-04,NaN,True,3,0.0

In [17]:
df_rcon.describe()

,CountyFipsCode,BuildingCode,StructureCode,StructureNbr,LandSqft,LivingSqft,GarageSqft,BasementSqft,BasementFinishedSqft,AtticSqft,Bedrooms,TotalRooms,TotalBaths,FirePlaces,YearBuilt,EffectiveYearBuilt,ConditionCode,QualityCode,GarageNoOfCars,PatioPorchCode,LandValue,ImprovementValue,TotalValue,AssessedYear,PropTaxAmount,City,Zip,Latitude,Longitude,BuildingShapeCode,ConstructionCode,Stories,UnitsInBuilding,FoundationCode,ExteriorCode,RoofCode,CoolingCode,HeatingSourceCode,View,ViewScore,LastSalePrice,DeedType,SellPrice,DistrsdProp,IsFixer
count,32902.000000,11256.000000,3.0,32902.000000,3.290200e+04,32902.000000,32902.000000,32902.000000,32902.000000,32902.0,32902.000000,32902.0,32902.000000,32902.000000,32902.000000,32902.0,32902.000000,32902.000000,32902.0,522.000000,3.290200e+04,3.290200e+04,3.290200e+04,32902.000000,32893.000000,0.0,32902.000000,32902.000000,32902.000000,0.0,32902.000000,32902.000000,32902.000000,27.0,57.000000,0.0,42.000000,1404.000000,9879.000000,32902.000000,3.290200e+04,0.0,2.198500e+04,32902.000000,32902.0
mean,26056.128868,3.052239,-1.0,0.999757,6.147412e+04,1133.080633,11.961188,16.207920,7.072883,0.0,1.880311,0.0,1.825581,0.320862,1982.841621,0.0,2.050058,6.381770,0.0,1.994253,4.117705e+04,1.811306e+05,2.223094e+05,2015.992067,2576.931475,NaN,55379.678409,33.490786,-94.593287,NaN,0.733420,1.235153,21.854750,8.0,5.368421,NaN,10.857143,2.269943,9.952121,0.765729,3.194584e+05,NaN,2.070887e+05,0.228527,0.0
std,19465.486063,3.453175,0.0,0.023389,1.769297e+05,3144.911885,66.242595,115.874763,58.321785,0.0,0.708913,0.0,0.645229,0.466815,12.478862,0.0,0.232634,1.252693,0.0,0.531147,4.574657e+05,9.042000e+05,1.259713e+06,0.188168,2960.705532,NaN,30798.861244,10.170521,19.956632,NaN,0.528476,3.023849,46.507234,0.0,1.576972,NaN,2.646410,0.689340,4.297152,1.070396,4.340805e+06,NaN,2.169017e+05,0.882176,0.0
min,12011.000000,1.000000,-1.0,0.000000,3.999000e+03,99.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,1950.000000,0.0,1.000000,0.000000,0.0,1.000000,0.000000e+00,1.700000e+01,1.000000e+03,2010.000000,0.000000,NaN,0.000000,25.962000,-122.518000,NaN,0.000000,0.000000,0.000000,8.0,0.000000,NaN,3.000000,1.000000,2.000000,0.000000,0.000000e+00,NaN,2.250000e+03,0.000000,0.0
25%,12011.000000,1.000000,-1.0,1.000000,3.999000e+03,840.000000,0.000000,0.000000,0.000000,0.0,1.000000,0.0,1.500000,0.000000,1974.000000,0.0,2.000000,6.000000,0.0,2.000000,7.559000e+03,6.576900e+04,7.457500e+04,2016.000000,935.000000,NaN,33065.000000,26.144000,-122.190000,NaN,0.000000,0.000000,1.000000,8.0,5.000000,NaN,12.000000,2.000000,12.000000,0.000000,6.000000e+04,NaN,8.250000e+04,0.000000,0.0
50%,12011.000000,1.000000,-1.0,1.000000,3.999000e+03,1040.000000,0.000000,0.000000,0.000000,0.0,2.000000,0.0,2.000000,0.000000,1980.000000,0.0,2.000000,6.000000,0.0,2.000000,1.502000e+04,1.163090e+05,1.384000e+05,2016.000000,1889.000000,NaN,33319.000000,26.233000,-80.257000,NaN,1.000000,0.000000,1.000000,8.0,5.000000,NaN,12.000000,2.000000,12.000000,0.000000,1.250000e+05,NaN,1.599000e+05,0.000000,0.0
75%,53033.000000,8.000000,-1.0,1.000000,1.535500e+04,1270.000000,0.000000,0.000000,0.000000,0.0,2.000000,0.0,2.000000,1.000000,1991.000000,0.0,2.000000,6.000000,0.0,2.000000,4.388900e+04,2.166590e+05,2.700000e+05,2016.000000,3291.000000,NaN,98032.000000,47.544000,-80.150000,NaN,1.000000,2.000000,12.000000,8.0,7.000000,NaN,12.000000,2.000000,12.000000,2.000000,2.300000e+05,NaN,2.650000e+05,0.000000,0.0
max,53033.000000,9.000000,-1.0,3.000000,3.236574e+06,408116.000000,1120.000000,3470.000000,2730.000000,0.0,9.000000,0.0,7.000000,1.000000,2016.000000,0.0,5.000000,9.000000,0.0,5.000000,7.019320e+07,1.047947e+08,1.421090e+08,2016.000000,97836.000000,NaN,98354.000000,47.859000,-80.076000,NaN,3.000000,43.000000,402.000000,8.0,7.000000,NaN,12.000000,6.000000,15.000000,4.000000,6.750000e+08,NaN,9.159830e+06,5.000000,0.0

In [18]:
print("Number of numerical predictors RCON: ", len(list(df_rcon.describe())))

Number of numerical predictors RCON:  45

In [19]:
df_rsfr.head()

,CountyFipsCode,BuildingCode,StructureCode,StructureNbr,LandSqft,LivingSqft,GarageSqft,BasementSqft,BasementFinishedSqft,AtticSqft,Bedrooms,TotalRooms,TotalBaths,FirePlaces,YearBuilt,EffectiveYearBuilt,Condition,ConditionCode,Quality,QualityCode,GarageCarportCode,GarageNoOfCars,HasPatioPorch,PatioPorchCode,HasPool,PoolCode,Zonning,LandValue,ImprovementValue,TotalValue,AssessedYear,PropTaxAmount,City,State,Zip,Latitude,Longitude,BuildingShapeCode,ConstructionCode,Stories,UnitsInBuilding,FoundationCode,ExteriorCode,RoofCode,CoolingCode,HeatingCode,HeatingSourceCode,IsWaterfront,View,ViewScore,LastSaleDate,LastSalePrice,DocType,DeedType,TransType,ArmsLengthFlag,DistressCode,StatusDate,SellDate,SellPrice,OwnerOccupied,DistrsdProp,IsFixer
0,12011,NaN,NaN,1,5250,1825,0,0,0,0,3,0,2.0,0,1989,0,AVE,3,QAV,6,NaN,0,True,5.0,True,Y,PRD-5Q,36749,208159,244910,2016,3262.0,NaN,FL,33322,26.149,-80.282,NaN,1,1,1,8.0,5.0,NaN,12.0,NaN,NaN,False,NaN,1,2004-10-06 00:00:00,294000,W,NaN,R,True,O,2017-04-15 11:48:00,2004-10-06,294000.0,True,1,0.0
1,12011,NaN,NaN,1,7817,971,0,0,0,0,0,0,0.0,0,1958,0,AVE,3,QAV,6,NaN,0,False,NaN,False,NaN,RS-5,23449,50479,73930,2016,1794.0,NaN,FL,33068,26.208,-80.213,NaN,1,1,1,8.0,5.0,NaN,12.0,NaN,NaN,False,NaN,0,2008-12-09 00:00:00,81000,G,NaN,R,True,S,2017-02-10 00:00:00,2008-12-09,81000.0,False,3,0.0
2,12011,NaN,NaN,1,5927,1859,0,0,0,0,3,0,2.0,0,1991,0,AVE,3,QAV,6,NaN,0,False,NaN,False,NaN,PUD,40009,232599,272610,2016,3112.0,NaN,FL,33323,26.134,-80.316,NaN,1,1,1,8.0,5.0,NaN,12.0,NaN,NaN,False,NaN,0,2006-08-28 00:00:00,375000,W,NaN,R,True,NaN,2017-02-10 00:00:00,2006-08-28,375000.0,True,0,0.0
3,12011,NaN,NaN,1,7053,1540,0,0,0,0,4,0,2.0,0,1960,0,AVE,3,QAV,6,NaN,0,False,NaN,False,NaN,R-1C,42319,148759,191080,2016,1774.0,NaN,FL,33023,26.009,-80.214,NaN,1,1,1,8.0,5.0,NaN,12.0,NaN,NaN,False,NaN,0,2004-03-25 00:00:00,193000,G,NaN,R,True,NaN,2017-02-10 00:00:00,2004-03-25,193000.0,True,0,0.0
4,12011,NaN,NaN,1,7931,1862,0,0,0,0,4,0,2.0,0,1977,0,AVE,3,QAV,6,NaN,0,False,NaN,False,NaN,RS-5,45599,170939,216540,2016,2161.0,NaN,FL,33322,26.152,-80.297,NaN,1,1,1,8.0,5.0,NaN,12.0,NaN,NaN,False,NaN,0,1998-06-29 00:00:00,113000,NaN,NaN,R,True,NaN,2017-02-10 00:00:00,1998-06-29,NaN,True,0,0.0

In [20]:
df_rsfr.describe()

,CountyFipsCode,BuildingCode,StructureCode,StructureNbr,LandSqft,LivingSqft,GarageSqft,BasementSqft,BasementFinishedSqft,AtticSqft,Bedrooms,TotalRooms,TotalBaths,FirePlaces,YearBuilt,EffectiveYearBuilt,ConditionCode,QualityCode,GarageNoOfCars,PatioPorchCode,LandValue,ImprovementValue,TotalValue,AssessedYear,PropTaxAmount,City,Zip,Latitude,Longitude,BuildingShapeCode,ConstructionCode,Stories,UnitsInBuilding,FoundationCode,ExteriorCode,RoofCode,CoolingCode,HeatingSourceCode,View,ViewScore,LastSalePrice,DeedType,SellPrice,DistrsdProp,IsFixer
count,85879.00000,52780.000000,1.0,85879.000000,8.587900e+04,85879.000000,85879.000000,85879.000000,85879.000000,85879.0,85879.000000,85879.0,85879.000000,85879.000000,85879.000000,85879.0,85879.000000,85879.000000,85879.0,34458.000000,8.587900e+04,8.587900e+04,8.587900e+04,85879.000000,85854.000000,0.0,85879.000000,85879.000000,85879.000000,0.0,85879.000000,85879.000000,85879.000000,32697.000000,32832.000000,1.0,26054.000000,52771.000000,12803.000000,85879.000000,8.587900e+04,0.0,3.963200e+04,85879.000000,85879.0
mean,37347.20445,1.022717,-1.0,1.010655,1.622282e+04,1874.517647,211.161623,355.455431,179.267341,0.0,2.827292,0.0,1.977003,0.535474,1975.227867,0.0,3.211914,6.523073,0.0,2.770097,1.850358e+05,2.680594e+05,4.530971e+05,2015.996542,5160.540091,NaN,73126.300947,39.357506,-106.169047,NaN,0.378812,1.386183,0.956031,8.231397,5.188048,24.0,11.994934,2.467757,4.705069,0.693336,2.938055e+05,NaN,3.825581e+05,0.244833,0.0
std,19935.47468,0.416729,NaN,0.133182,6.083578e+04,1029.014108,281.659989,653.931705,385.812408,0.0,1.460753,0.0,1.210666,0.498743,18.869927,0.0,0.485548,1.243311,0.0,1.322711,2.843866e+05,4.280534e+05,6.377382e+05,0.121223,4094.548236,NaN,31643.595395,10.409928,20.398196,NaN,0.487082,0.510940,0.347963,1.718927,1.963427,NaN,0.196633,0.753664,3.734096,1.041690,4.413295e+06,NaN,3.645303e+05,0.914076,0.0
min,12011.00000,1.000000,-1.0,0.000000,3.999000e+03,99.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,1950.000000,0.0,1.000000,0.000000,0.0,1.000000,9.900000e+01,4.990000e+02,1.100000e+03,2010.000000,0.000000,NaN,0.000000,25.957000,-122.526000,NaN,0.000000,0.000000,0.000000,8.000000,5.000000,24.0,3.000000,1.000000,2.000000,0.000000,0.000000e+00,NaN,2.667000e+03,0.000000,0.0
25%,12011.00000,1.000000,-1.0,1.000000,5.859000e+03,1264.000000,0.000000,0.000000,0.000000,0.0,2.000000,0.0,1.000000,0.000000,1957.000000,0.0,3.000000,6.000000,0.0,2.000000,5.579400e+04,1.504890e+05,2.400000e+05,2016.000000,3090.000000,NaN,33313.000000,26.178000,-122.284000,NaN,0.000000,1.000000,1.000000,8.000000,5.000000,24.0,12.000000,2.000000,2.000000,0.000000,1.180000e+05,NaN,2.110000e+05,0.000000,0.0
50%,53033.00000,1.000000,-1.0,1.000000,7.741000e+03,1650.000000,0.000000,0.000000,0.000000,0.0,3.000000,0.0,2.000000,1.000000,1976.000000,0.0,3.000000,6.000000,0.0,2.000000,1.179990e+05,2.179990e+05,3.520000e+05,2016.000000,4437.000000,NaN,98027.000000,47.386000,-122.108000,NaN,0.000000,1.000000,1.000000,8.000000,5.000000,24.0,12.000000,2.000000,3.000000,0.000000,2.052000e+05,NaN,3.050000e+05,0.000000,0.0
75%,53033.00000,1.000000,-1.0,1.000000,1.070400e+04,2262.000000,440.000000,670.000000,0.000000,0.0,4.000000,0.0,3.000000,1.000000,1992.000000,0.0,3.000000,8.000000,0.0,5.000000,2.429990e+05,3.099990e+05,5.400000e+05,2016.000000,6222.000000,NaN,98092.000000,47.605000,-80.276000,NaN,1.000000,2.000000,1.000000,8.000000,5.000000,24.0,12.000000,3.000000,8.000000,1.000000,3.394500e+05,NaN,4.475000e+05,0.000000,0.0
max,53033.00000,9.000000,-1.0,4.000000,6.542712e+06,69854.000000,5430.000000,14610.000000,9740.000000,0.0,128.000000,0.0,68.000000,1.000000,2016.000000,0.0,6.000000,10.000000,0.0,5.000000,2.617600e+07,9.881800e+07,1.249940e+08,2016.000000,94182.000000,NaN,98354.000000,47.778000,-80.077000,NaN,3.000000,7.000000,68.000000,21.000000,29.000000,24.0,12.000000,6.000000,15.000000,3.000000,1.280000e+09,NaN,2.200000e+07,5.000000,0.0

In [21]:
print("Number of numerical predictors RSFR: ", len(list(df_rsfr.describe())))

Number of numerical predictors RSFR:  45

## Non-numerical columns

In [22]:
df_rcon.select_dtypes(include=object).columns.tolist()

['Condition',
 'Quality',
 'GarageCarportCode',
 'PoolCode',
 'Zonning',
 'State',
 'HeatingCode',
 'LastSaleDate',
 'DocType',
 'TransType',
 'DistressCode',
 'StatusDate',
 'SellDate']

In [23]:
df_rcon[df_rcon.select_dtypes(include=object).columns.tolist()].head()

,Condition,Quality,GarageCarportCode,PoolCode,Zonning,State,HeatingCode,LastSaleDate,DocType,TransType,DistressCode,StatusDate,SellDate
0,AVE,QAV,NaN,NaN,NaN,FL,NaN,1998-03-27 00:00:00,NaN,R,NaN,2017-02-10 00:00:00,1998-03-27
1,AVE,QAV,NaN,NaN,NaN,FL,NaN,2006-10-06 00:00:00,W,R,NaN,2017-02-10 00:00:00,2006-10-06
2,AVE,QAV,NaN,NaN,RM-18,FL,NaN,2003-12-05 00:00:00,G,R,NaN,2017-02-10 00:00:00,2003-12-05
3,AVE,QAV,NaN,NaN,NaN,FL,NaN,2006-11-28 00:00:00,W,R,NaN,2017-02-10 00:00:00,2006-11-28
4,AVE,QAV,NaN,NaN,R-4C,FL,NaN,2009-03-04 00:00:00,G,R,S,2017-02-10 00:00:00,2009-03-04

In [24]:
df_rsfr.select_dtypes(include=object).columns.tolist() == df_rcon.select_dtypes(include=object).columns.tolist()

True

As it can be seen from the above output the same non-numerical columns are appering in the RSFR dataframe.

It seems to be a pattern for each value from the __date__ column. I am going to verify if each value ends with 'T000000'. If yes, I am going to drop that part since it has no relevance for the model due to the fact that every temporary detail about hour, minutes, seconds in which the house was sold is set on 0.

In [25]:
df_rsfr['SellDate']

0        2004-10-06
1        2008-12-09
2        2006-08-28
3        2004-03-25
4        1998-06-29
            ...
53036    2004-01-08
53037    1987-11-09
53038    1989-08-09
53039    1992-04-28
53040    2006-07-11
Name: SellDate, Length: 85879, dtype: object

In [26]:
skew(df_rcon1['CountyFipsCode'])

0.0

In [27]:
skew(df_rcon1['StructureCode'])

nan

In [28]:
print(df_rcon1.dtypes)

CountyFipsCode      int64
BuildingCode      float64
StructureCode     float64
StructureNbr        int64
LandSqft            int64
                   ...
SellDate           object
SellPrice         float64
OwnerOccupied        bool
DistrsdProp         int64
IsFixer           float64
Length: 63, dtype: object

In [29]:
df_rcon1['BuildingCode'].value_counts(normalize=True)

Series([], Name: BuildingCode, dtype: float64)

In [30]:
# del df_rcon1['BuildingCode']

In [31]:
for obs in list(df_rcon1['StructureCode']):
    if not pd.isnull(obs):
        print(obs)

-1.0

In [32]:
# del df_rcon1['StructureCode']